# fly.toml file generated for appkata-redistls on 2020-11-23T17:04:32Z

app = "appkata-redistls"


[[mounts]]
  source = "redis_server"
  destination = "/data"

[[services]]
  internal_port = 7379
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = []
    port = "10000"

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
