# fly.toml file generated for redis-tlsnoauth on 2020-11-11T13:01:50Z

app = "redis-tlsnoauth"

[[mounts]]
source      = "redis_server"
destination = "/data"

[[services]]
  internal_port = 6379
  protocol = "tcp"

  [services.concurrency]
  hard_limit = 25
  soft_limit = 20

  [[services.ports]]
  handlers = [ "tls" ]
  port     = "10000"

  [[services.tcp_checks]]
  interval = 10000
  timeout  = 2000
